
[package]
name = "simd-doc"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
doc = { path = "../doc" }

cxx = "1.0"
memchr = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
rkyv = { workspace = true }

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
allocator = { path = "../allocator" }

quickcheck = { workspace = true }
hexdump = { workspace = true }
insta = { workspace = true }
