
[package]
name = "simd-doc"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
doc = { path = "../doc" }

cxx = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
cxx-build = "1.0"
