
[package]
name = "dekaf"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
doc = { path = "../doc" }
gazette = { path = "../gazette" }
simd-doc = { path = "../simd-doc" }

memchr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
cxx-build = "1.0"
